use sqlchallange;
-- Query related to products
-- 1.Top selling product:Find product sold in highest
 select p.product_name, sum(od.quantity) as total_quantity_sold
 from cleaned_products p
   join cleaned_order_details od on p.product_id = od.product_id
group by p.product_name
order by total_quantity_sold desc
limit 1

-- 2.Least selling products:find the lowerst selling product
select p.product_name, sum(od.quantity) as total_quantity_sold
 from cleaned_products p
   join cleaned_order_details od on p.product_id = od.product_id
group by p.product_name
order by total_quantity_sold asc
limit 1

-- 3.Revenue per product:Find revenue generated by each product
select p.product_name, sum(p.price * od.quantity) as total_revenue
 from cleaned_products p
   join cleaned_order_details od on p.product_id = od.product_id
group by p.product_name

-- 4.Category wise sales:Find total sales for each category
    select p.category, sum(p.price * od.quantity) as total_revenue
 from
    cleaned_products p
    join cleaned_order_details od
     on p.product_id = od.product_id
       
group by p.category

-- 5.Most expensive product sold:Find highest price product that was sold
select p.product_id, p.product_name, p.price
 from cleaned_products p
   join cleaned_order_details od on p.product_id = od.product_id    
        order by p.price desc
        limit 1

-- 6. Avg price per category:  find avg product price category wise
select p.category, avg(p.price) as avg_price
    from cleaned_products p
group by p.category
    order by avg_price desc        

-- 7.Product demand Trend: Find daily quantity sold for each product
SELECT 
    p.product_name, 
    od.order_date, 
    SUM(odd.quantity) AS daily_quantity_sold
FROM cleaned_products p
-- 1. Connect products to their specific line items
JOIN cleaned_order_details odd 
    ON p.product_id = odd.product_id 
-- 2. Connect those line items to the main order info to get the date
JOIN cleaned_orders od 
    ON odd.order_id = od.order_id
GROUP BY 
    p.product_name, 
    od.order_date
ORDER BY 
    p.product_name, 
    od.order_date;



describe cleaned_products;