use sqlchallange;
-- 1.Total Revenue:Find total revenue 
select sum(payment_amount)as total_revenue
from cleaned_payment

-- 2.Revenue by date:Find date revenue
select
payment_date,
sum(payment_amount)as daily_revenue
from cleaned_payment
group by payment_date
order by payment_date

-- 3.Revenue by month:find monthly revenue
select 
month(payment_date) as month_no,
monthname(payment_date)as month_name,
sum(payment_amount)
from cleaned_payment
group by month(payment_date),
monthname(payment_date)
order by month_no

-- 4.Revenue by product:find revenue generated by each product
 select p.product_id,p.product_name,sum(p.price*od.quantity)as total_revenue
 from cleaned_products p
join cleaned_order_details od
on p.product_id=od.product_id
group by p.product_id,p.product_name
order by total_revenue desc;

-- 5.Revenue by customer:Find customer wise revenue
select c.customer_id,c.customerr_name,sum(p.payment_amount)as customer_revenue
from cleaned_customers c
join cleaned_orders o on
c.customer_id=o.customer_id
join cleaned_payment p
on o.order_id=p.order_id
group by c.customer_id ,c.customerr_name
order by customer_revenue desc

-- 6.Revenue by category:Find category wise revenue
select 
pr.category,
sum(price* od.quantity)as total_revenue
from cleaned_products pr
join cleaned_order_details od
on pr.product_id=od.product_id
group by pr.category
order by total_revenue

7.High Revenue days:Find days generating high revenue
select
payment_date,
sum(payment_amount)as total_revenue
from cleaned_payment
group by payment_date
order by total_revenue
